enable-module-update = false # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
enabled = false
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "apk"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Gboard]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "jasonwu1994/Gboard-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Jasonwu"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/unix-custom-apk/apks/com.google.android.inputmethod.latin"

[Gboard2]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Jkennethcarino"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/unix-custom-apk/apks/com.google.android.inputmethod.latin"

[TaskManager]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Paresh"
direct-dlurl = "https://github.com/RohitKushvaha01/TaskManager/releases/download/v1.5.2/taskmanager-v1.5.2.apk"
archive-dlurl = "https://archive.org/download/unix-custom-apk/apks/com.rohit.taskmanager"

[GooglePhotos]
enabled = true
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/unix-custom-apk/apks/com.google.android.apps.photos"

[Twitter]
enabled = false
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "module"
version = "11.81.0-release.0"
include-stock = "split"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
